name: code_climate
on: [push]
jobs:
  check_cov:
    runs-on: ubuntu-latest
    steps:
      - name: Check coverage
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Check Code
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 0ad30785c211f4a17f308edbb4d6179b562ea25368add736a6325bf48024efe9
        with:
          coverageCommand: make coverage
          coverageLocations: ${{github.workplace}}/coverage.xml
